### ISSUE TITLE
FilPunks: Cannot copy text from "Congratulations"-message

### ISSUE THREAD

**Issue by lksbrssr** [FilPunks/nft-project#2]
Steps to reproduce:
- Mint a FIL punk
- Review "Congratulations" note
- Move cursor over text (e.g., IPFS CID)

Expected outcome:
- Cursor should allow you to mark text and copy-paste it elsewhere

Actual outcome:
- Congratulations text is an image so one cannot select on it with the cursor

**Comment by Fatman13** [comment]
Thanks for catching! Added [selectable tag](https://github.com/fancyapps/fancybox/issues/1852) to popup. Should be able to select text now.
