### ISSUE TITLE
FilPunks: Server timed out after signing transaction

### ISSUE THREAD

**Issue by lksbrssr** [FilPunks/nft-project#5]
![Image](https://github.com/FilPunks/nft-project/assets/82394590/6c396504-eb4c-42d6-b17c-9c6263d819b0)

**Comment by Fatman13** [comment]
Thanks for reporting! This is likely to be result of unstable [node service](https://chainlist.org/?testnets=true&search=filecoin) user's MetaMask is connecting to. If MetaMask failed, it won't prompt the frontend to pop the mint result. We received similar reports from other users too and unfortunately there is not too much could be done on DApp's side to mitigate this issue.
